server:
  port: 9090

spring:
  application:
    name: account-service

  sql:
    init:
      mode: always

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: "optional:config-server:http://localhost:8888/"

  profiles:
    active: qa

build:
  version: "1.0"

accounts:
  message: "Welcome to kasiarakos accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345

management:
  endpoints:
    web:
      exposure:
        include: "*"

